"""
hartree_fock.py — Restricted Hartree-Fock (RHF) SCF for 1D H2.

Approximation
-------------
The RHF Fock operator is built in two explicit steps that mirror
what is done in mean_field.py:

  Step 1 — Hartree potential (same as mean_field.py):
      V_H[rho](x) = integral rho(x') / sqrt((x-x')^2 + a^2) dx'
      with the TOTAL density rho = 2|phi|^2.
      This potential includes self-interaction.

  Step 2 — Exchange potential (removes self-interaction):
      For a single doubly-occupied real orbital, the exchange operator
      acting on phi gives a local potential equal to V_H[|phi|^2]:
          V_K(x) = V_H[|phi|^2](x)
      Subtracting V_K from V_H cancels the self-interaction exactly.

The HF Fock operator is therefore:
    F = h + V_H[rho] - V_K = h + V_H[2|phi|^2] - V_H[|phi|^2]
      = h + V_H[|phi|^2]

Total energy:
    E = 2*eps - K_11 + V_nn

where K_11 = J_11 = integral |phi|^2 * V_K dx is the exchange integral
(equal to the Coulomb integral for a single real orbital).

Convergence uses Fock-matrix mixing:
    F_mixed = (1 - alpha) * F_old + alpha * F_new    (for iterations > 0)

Usage
-----
    python hartree_fock.py
"""

import numpy as np
import scipy.linalg as la

from potentials import v_en, v_nn, v_hartree
from utils import make_grid, kinetic_matrix, normalize
from plot import plot_orbital_and_density

# ── Parameters ────────────────────────────────────────────────────────────────
R        = 1.4    # Internuclear distance (a.u.)
a        = 0.1    # Soft-Coulomb softening parameter
L        = 10.0   # Half-box size (a.u.)
N        = 400    # Number of grid points

max_iter = 100    # Maximum SCF iterations
conv_tol = 1e-8   # Convergence threshold on |delta E|
mixing   = 0.5    # Fock matrix mixing parameter (0=no update, 1=full replacement)


# ── Helper functions ──────────────────────────────────────────────────────────

def v_exchange(phi, x, dx, a):
    """Exchange potential for a single doubly-occupied real spatial orbital.

    For a closed-shell two-electron system with one occupied orbital phi(x),
    the non-local HF exchange operator acting on phi reduces to a local
    multiplicative potential:

        V_K(x) = integral |phi(x')|^2 / sqrt((x-x')^2 + a^2) dx'
               = V_H[|phi|^2](x)

    This is identical to the Hartree potential generated by the single-orbital
    density |phi|^2 (half the total density rho = 2|phi|^2).

    Subtracting V_K from the Hartree potential V_H[rho] in the Fock operator
    exactly cancels the self-interaction error:
        V_H[rho] - V_K = V_H[2|phi|^2] - V_H[|phi|^2] = V_H[|phi|^2] = V_K

    Parameters
    ----------
    phi : ndarray, shape (N,)
        Spatial orbital (normalised).
    x : ndarray, shape (N,)
        Spatial grid.
    dx : float
        Grid spacing.
    a : float
        Soft-Coulomb softening parameter.

    Returns
    -------
    ndarray, shape (N,)
        Exchange potential V_K(x) = V_H[|phi|^2](x).
    """
    return v_hartree(phi**2, x, dx, a)


def compute_energy(eps, phi, x, dx, a, R):
    """Compute the RHF total energy.

    E = 2*eps - K_11 + V_nn

    K_11 = J_11 = integral |phi|^2 * V_K(x) dx
    where V_K = V_H[|phi|^2] is the exchange potential.

    Parameters
    ----------
    eps : float
        Orbital energy (lowest eigenvalue of the Fock operator).
    phi : ndarray, shape (N,)
        Converged spatial orbital.
    x : ndarray, shape (N,)
        Spatial grid.
    dx : float
        Grid spacing.
    a : float
        Soft-Coulomb softening parameter.
    R : float
        Internuclear distance (a.u.).

    Returns
    -------
    float
        Total energy in atomic units.
    """
    V_K = v_exchange(phi, x, dx, a)             # exchange potential
    K11 = np.trapz(phi**2 * V_K, x)            # K_11 = J_11 for single real orbital
    return 2.0 * eps - K11 + v_nn(R, a)


def run_scf(x, dx, R, a, max_iter, conv_tol, mixing):
    """Run the RHF SCF with Fock-matrix mixing.

    Parameters
    ----------
    x : ndarray, shape (N,)
        Spatial grid.
    dx : float
        Grid spacing.
    R : float
        Internuclear distance (a.u.).
    a : float
        Soft-Coulomb softening parameter.
    max_iter : int
        Maximum number of SCF iterations.
    conv_tol : float
        Convergence threshold on |delta E|.
    mixing : float
        Fock matrix mixing parameter.

    Returns
    -------
    phi : ndarray, shape (N,)
        Converged spatial orbital.
    eps : float
        Converged orbital energy (a.u.).
    E : float
        Converged total energy (a.u.).
    """
    N = len(x)

    # core Hamiltonian (constant throughout SCF)
    T      = kinetic_matrix(N, dx)
    H_core = T + np.diag(v_en(x, R, a))

    # initial guess: lowest eigenstate of H_core
    evals, evecs = la.eigh(H_core)
    phi = normalize(evecs[:, 0], dx)
    if phi[np.argmax(np.abs(phi))] < 0:
        phi = -phi

    F_old = None
    E_old = 0.0

    print(f"{'Iter':>4}  {'eps (a.u.)':>14}  {'E_total (a.u.)':>16}  {'delta E':>12}")
    print("-" * 54)

    for it in range(max_iter):
        # ── Step 1: Hartree potential (same as mean_field.py) ─────────────────
        # Uses total density rho = 2|phi|^2; includes self-interaction.
        rho = 2.0 * phi**2
        V_H = v_hartree(rho, x, dx, a)

        # ── Step 2: Exchange potential (removes self-interaction) ──────────────
        # For a single doubly-occupied real orbital:
        #   V_K(x) = V_H[|phi|^2](x)  =  V_H / 2
        V_K = v_exchange(phi, x, dx, a)

        # ── HF Fock operator: Hartree minus exchange ───────────────────────────
        F_new = H_core + np.diag(V_H - V_K)

        # Fock-matrix mixing
        if it > 0:
            F = (1.0 - mixing) * F_old + mixing * F_new
        else:
            F = F_new

        F_old = F

        # diagonalise mixed Fock matrix
        evals, evecs = la.eigh(F)
        eps     = evals[0]
        phi_new = evecs[:, 0]
        phi_new = normalize(phi_new, dx)
        if phi_new[np.argmax(np.abs(phi_new))] < 0:
            phi_new = -phi_new

        phi = phi_new

        E       = compute_energy(eps, phi, x, dx, a, R)
        delta_E = abs(E - E_old)
        print(f"{it + 1:>4}  {eps:>14.8f}  {E:>16.8f}  {delta_E:>12.4e}")

        if delta_E < conv_tol:
            print("-" * 54)
            print(f"SCF converged after {it + 1} iterations.")
            break

        E_old = E
    else:
        print("-" * 54)
        print(f"WARNING: SCF did not converge within {max_iter} iterations.")

    return phi, eps, E


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    x, dx = make_grid(L, N)

    print("=" * 54)
    print("Restricted Hartree-Fock (RHF) SCF for 1D H2")
    print("=" * 54)

    phi, eps, E = run_scf(x, dx, R, a, max_iter, conv_tol, mixing)

    # Hartree and exchange potentials at convergence
    rho = 2.0 * phi**2
    V_H = v_hartree(rho, x, dx, a)          # same as mean_field.py
    V_K = v_exchange(phi, x, dx, a)         # exchange = V_H / 2

    # Coulomb and exchange integrals (equal for single real orbital)
    J11 = np.trapz(phi**2 * V_H, x) / 2.0  # J_11 = (1/2) * <rho|V_H>
    K11 = np.trapz(phi**2 * V_K, x)        # K_11 = <phi^2|V_K>

    print()
    print(f"  R                   = {R:.4f} a.u.")
    print(f"  Orbital energy  eps = {eps:.6f} a.u.")
    print(f"  V_nn                = {v_nn(R, a):.6f} a.u.")
    print(f"  J_11 (Coulomb)      = {J11:.6f} a.u.")
    print(f"  K_11 (Exchange)     = {K11:.6f} a.u.  (= J_11 for closed-shell H2)")
    print(f"  Total energy    E   = {E:.6f} a.u.")
    print("=" * 54)

    title = (f"Hartree-Fock RHF SCF  |  R = {R} a.u.\n"
             f"E = 2*eps - K_11 + V_nn = {E:.4f} a.u.")
    plot_orbital_and_density(x, phi, 2.0 * phi**2, R, title,
                             filename="h2_hartree_fock.png")


if __name__ == "__main__":
    main()
