"""
potentials.py — Soft Coulomb potential functions for the 1D H2 model.

All potentials use atomic units (hbar = m_e = e = 1) and the soft Coulomb form
    V(r) = 1 / sqrt(r^2 + a^2)
which avoids the singularity at r = 0 and makes the 1D model physically
reasonable.  The softening parameter a is shared by every interaction.
"""

import numpy as np


def soft_coulomb(r, a):
    """Return the soft Coulomb kernel 1/sqrt(r^2 + a^2).

    Parameters
    ----------
    r : float or ndarray
        Distance(s).
    a : float
        Softening parameter (> 0).

    Returns
    -------
    float or ndarray
        Soft Coulomb value(s).
    """
    return 1.0 / np.sqrt(r**2 + a**2)


def v_en(x, R, a):
    """Electron-nuclear attraction potential for H2.

    Two protons fixed at ±R/2; potential is attractive (negative).

    Parameters
    ----------
    x : ndarray, shape (N,)
        Electron coordinate grid.
    R : float
        Internuclear distance (a.u.).
    a : float
        Soft-Coulomb softening parameter.

    Returns
    -------
    ndarray, shape (N,)
        V_en(x) = -1/sqrt((x-R/2)^2+a^2) - 1/sqrt((x+R/2)^2+a^2)
    """
    return -soft_coulomb(x - R / 2.0, a) - soft_coulomb(x + R / 2.0, a)


def v_nn(R, a):
    """Nuclear-nuclear repulsion for H2.

    Parameters
    ----------
    R : float
        Internuclear distance (a.u.).
    a : float
        Soft-Coulomb softening parameter.

    Returns
    -------
    float
        V_nn = 1/sqrt(R^2 + a^2)
    """
    return soft_coulomb(R, a)


def v_hartree(density, x, dx, a):
    """Hartree (Coulomb) potential generated by an electron density.

    Uses a fully vectorised matrix-vector product:
        V_H(x_i) = sum_j  density(x_j) / sqrt((x_i - x_j)^2 + a^2) * dx

    Parameters
    ----------
    density : ndarray, shape (N,)
        Electron density rho(x) (not normalised to any particular value here;
        caller is responsible for passing the correct rho).
    x : ndarray, shape (N,)
        Spatial grid.
    dx : float
        Grid spacing.
    a : float
        Soft-Coulomb softening parameter.

    Returns
    -------
    ndarray, shape (N,)
        Hartree potential V_H(x).
    """
    # r[i, j] = x[i] - x[j]
    r = x[:, None] - x[None, :]          # shape (N, N)
    K = soft_coulomb(r, a)               # shape (N, N)
    return (K @ density) * dx
